name: cvapp
description: CV application
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.2.5
  logging: ^1.2.0
  ui_components:
    path: packages/ui_components

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/ava.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: CVIcons
      fonts:
        - asset: icons/CVIcons.ttf

# run: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"